Add send form, check mistakes
htmlacademy-react/1485695-six-cities-9 pull request #10
Opened 2022-04-01 20:45 UTC by nadyavilboa

2022-04-02 10:06 UTC, Finnko requested changes

2022-04-02 10:06 UTC, Finnko commented on project/src/pages/room/room.tsx
> +  if (!currentOffer || !comments || !otherOffers) {
Давай подумаем с точки зрения пользователя. Если падает запрос на комментарии, это стоит того чтобы не показать мне целую страницу с оффером? Или места неподалеку? Как по мне здесь один критически важный запрос, если упадут остальные покажем нотифай но не вижу надобности блокировать страницу

2022-04-02 10:06 UTC, Finnko commented on project/src/pages/room/room.tsx
>    const currentId = Number(params.id?.slice(1));
А зачем слайс?

2022-04-02 10:06 UTC, Finnko commented on project/src/pages/room/room.tsx
> +
Галерею с изображениями надо обрезать до 6 штук. Заодно отовсюду можно убрать optional chaining так как мы уже дойдя до рендера точно будем знать что офферы есть

2022-04-02 10:06 UTC, Finnko commented on project/src/pages/room/room.tsx
> +              offers={[currentOffer, ...otherOffers]}
Места неподалеку ограничиваем до 3 максимум

2022-04-02 10:06 UTC, Finnko commented on project/src/store/api-actions.ts
> +      errorHandle(error);
Функцию следует переименовать на handleError

2022-04-02 10:06 UTC, Finnko commented on project/src/store/reducer.ts
> +  comments: Comments | null,
Для комментов и офферов неподалеку надо убрать null

2022-04-02 10:06 UTC, Finnko commented on project/src/store/reducer.ts
> +  comments: null,
Начальное состояние пустой массив

2022-04-03 18:04 UTC, nadyavilboa commented on project/src/pages/room/room.tsx
>    const currentId = Number(params.id?.slice(1));
потому что params дает :8 вместо просто 8. Нужен второй символ и Number

2022-04-03 18:54 UTC, nadyavilboa commented on project/src/pages/room/room.tsx
> +  const otherOffers = useAppSelector((state) => state.otherOffers);
так и у меня в начале функции. Или надо из функции вытащить?

2022-04-03 21:06 UTC, nadyavilboa commented on project/src/store/reducer.ts
> +  comments: Comments | null,
когда приложение запустилось на главной, никакого конкретного оффера еще нет и получается там null

2022-04-05 09:59 UTC, merged