Add mock data, types
htmlacademy-react/1485695-six-cities-9 pull request #5
Opened 2022-02-25 17:46 UTC by nadyavilboa

2022-02-25 19:36 UTC, Finnko requested changes
Не сделаны пункты:
Создайте новый компонент «Список предложений». Компонент должен отрисовывать карточки с предложениями аренды с помощью компонента «Карточка предложения». Все необходимые данные компонент принимает через props.

Добавьте в состояние компонента активную карточку с предложением (объект с данными предложения или только уникальный идентификатор предложения). Под активной карточкой предложения подразумевается карточка, на которую пользователь навёл курсор. Состояние пригодится нам в дальнейшем для реализации отображения маркеров предложений на карте.

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
>    return (
Я бы наверно предпочел чтобы не таскать везде offer.что-то достать все поля деструктуризацией

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +import { MULTIPLER } from '../../const/general';
Это не должно быть в константах и почему 10? Будет нагляднее если ты покажешь как это получается просто поделив одно на другое.

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +      {offer.isPremium ? <Badge className="place-card__mark" /> : ''}
В реакте есть conditional rendering, давай договоримся что такие конструкции мы не используем) 
```suggestion
      {offer.isPremium && <Badge className="place-card__mark" />}
```

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +          <img className="place-card__image" src={offer.previewImage} width="260" height="200" alt="Place image" />
В альт можно положить title. Понятно что это тоже неидеальное решение но лучше чем текущее

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
>          <p className="place-card__type">Apartment</p>
Тип апартов так же приходит. Обрати внимание что он с большой буквы

2022-02-25 19:36 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +            <span style={{width: offer.rating*MULTIPLER}}></span>
Сделай или функцию хелпер или здесь покажи что на что делишь. В текущем варианте несколько непрозрачно

2022-02-25 19:36 UTC, Finnko commented on project/src/components/places-list/places-list.tsx
> +  const placeArray = new Array(offers.length);
Это зачем? у нас же есть моки?

2022-02-25 19:36 UTC, Finnko commented on project/src/components/places-list/places-list.tsx
> +  offers.forEach((offer, index) => placeArray[index] = <PlaceCard className="cities__place-card" offer={offer}/>);
Мутация входящих пропсов + опять же непонятно для чего если массив предложений мы получаем от родителя

2022-02-25 19:36 UTC, Finnko commented on project/src/components/sort/sort.tsx
> +      <span className="places__sorting-caption">Sort by </span>
Он точно отображается в верстке?

2022-02-25 19:36 UTC, Finnko commented on project/src/components/tabs-item/tabs-item.tsx
> +import {DEFAULT_CITY} from '../../const/general';
Лишняя константа, по тз дефолт это Париж CITIES[0]

2022-02-25 19:36 UTC, Finnko commented on project/src/components/tabs-item/tabs-item.tsx
> +      <a className={`locations__item-link tabs__item ${cityName === DEFAULT_CITY ? 'tabs__item--active' : ''}`} href="#">
Для этого у нас есть пакет classnames. Поставь его в проект и мы сможем классы накидывать по условию. Для простого варианта выигрыш не очевиден, но для 2-3 уже понятно зачем. Так это своего рода дефолтное решение то давай его придерживаться
```suggestion
      <a className={cn('locations__item-link', 'tabs__item', {'tabs__item--active': cityName === DEFAULT_CITY})} href="#">
```
где cn  импорт из classnames

2022-02-25 19:36 UTC, Finnko commented on project/src/components/tabs/tabs.tsx
> +          {CITIES.map((city) => <TabsItem className='locations__item' cityName={city} key={city} />)}
Зачем изменила? Обычно двойные в jsx

2022-02-28 21:23 UTC, Finnko requested changes

2022-02-28 21:23 UTC, Finnko commented on project/src/components/favorites-card/favorites-card.tsx
> +function FavoritesCard({className, offer}: FavoritesCardProps): JSX.Element {
Это такая же карточка как и на главной немного отличаются размеры фото. Не стоит плодить сущности, заведи доп пропс isSmall например

2022-02-28 21:23 UTC, Finnko commented on project/src/components/favorites-card/favorites-card.tsx
> +      <div className="favorites__image-wrapper place-card__image-wrapper">
favorites__image-wrapper проверь что этот стиль действительно что-то дает. Потому что с местами неподалеку он идет мертвым грузом

2022-02-28 21:23 UTC, Finnko commented on project/src/components/favorites-card/favorites-card.tsx
> +          <img className="place-card__image" src={previewImage} width="260" height="200" alt={title} />
В карточке избранного картинки меньше

2022-02-28 21:23 UTC, Finnko commented on project/src/components/favorites-card/favorites-card.tsx
> +            <span style={{width: rating*100|MAX_RATING}}></span>
Подправь, видимо опечаталась

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +};
1. Что за интересный способ new Array(0);  объявить пустой массив? Давай использовать все таки общепринятое = []
2. Делаешь цикл в цикле. Данные можно сгруппировать за 1 проход. Заведи пустой объект, ключ название города, значение массив объектов с этим городом. Желательно потом сделать через reduce

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +  const filterOffers = offers.offers.filter(isFavorites);
Еще 1 проход) Но конкретно его можно оставить для наглядности

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +  const groupOffers = getGroupOffers(filterOffers);
Мне кажется больше подходит название 
```suggestion
  const groupOffers = mapOffersToCities(filterOffers);
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/main/main.tsx
> +  const setActiveOffer = useState(0)[1];
Надя разве в демо проекте используют такую запись?
```suggestion
  const [, setActiveOffer] = useState(0);
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/main/main.tsx
> +    );
Это не нужно, записывай просто айди

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/main/main.tsx
> +    currentOffer&&setActiveOffer(currentOffer.id);
Сюда приходит новый айди поэтому просто 
```suggestion
    setActiveOffer(cardId);
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/main/main.tsx
> +              <PlacesList className="cities__places-list" offers={offers} onMouseOver={onMouseOver}/>
Лучше более предметно назвать коллбек чтобы было более понятно 
```suggestion
              <PlacesList className="cities__places-list" offers={offers} onCardHover={handleMouseOver}/>
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/main/main.tsx
> +  const onMouseOver = (cardId: number) => {
Обрабочтики через handle + что-то
```suggestion
  const handleMouseOver = (cardId: number) => {
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/room/room.tsx
> +  const params = useParams();
```suggestion
  const { id } = useParams();
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/room/room.tsx
> +  const currentId = Number(params.id?.slice(1));
Зачем слайс?

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/room/room.tsx
> +  const currentOffer = offers.offers.find((offer: Offer)=>offer.id===currentId);
```suggestion
  const currentOffer = offers.offers.find((offer: Offer) => offer.id === currentId);
```

2022-02-28 21:23 UTC, Finnko commented on project/src/pages/room/room.tsx
> +                  {currentOffer?.bedrooms} Bedrooms
Если 1 то bedroom

2022-02-28 21:23 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +function PlaceCard(props: PlaceCardProps): JSX.Element {
```suggestion
function PlaceCard({className, offer, onMouseOver}: PlaceCardProps): JSX.Element {
```

2022-02-28 21:23 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +  const {className, offer, onMouseOver} = props;
```suggestion
```

2022-02-28 21:23 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +    <article className={`${className} place-card`} onMouseOver={cardItemMouseHoverHandler}>
Здесь можно не выносить отдельно 
```suggestion
    <article className={`${className} place-card`} onMouseOver={() => onCardHover(id)}>
```

2022-03-01 17:12 UTC, nadyavilboa commented on project/src/components/favorites-card/favorites-card.tsx
> +function FavoritesCard({className, offer}: FavoritesCardProps): JSX.Element {
ok

2022-03-01 17:12 UTC, nadyavilboa commented on project/src/components/favorites-card/favorites-card.tsx
> +          <img className="place-card__image" src={previewImage} width="260" height="200" alt={title} />
ok

2022-03-01 17:13 UTC, nadyavilboa commented on project/src/components/favorites-card/favorites-card.tsx
> +            <span style={{width: rating*100|MAX_RATING}}></span>
ok

2022-03-01 17:16 UTC, nadyavilboa commented on project/src/pages/favorites/favorites.tsx
> +};
1. тогда получаем неявый тип any
2. пока не сделано - сложно

2022-03-01 17:17 UTC, nadyavilboa commented on project/src/pages/room/room.tsx
> +  const currentOffer = offers.offers.find((offer: Offer)=>offer.id===currentId);
ok

2022-03-01 17:21 UTC, nadyavilboa commented on project/src/pages/room/room.tsx
> +                  {currentOffer?.bedrooms} Bedrooms
ok

2022-03-01 17:23 UTC, nadyavilboa commented on project/src/components/place-card/place-card.tsx
> +function PlaceCard(props: PlaceCardProps): JSX.Element {
еще один пропс добавился (уже 4). Предлагаю так оставить, а то строка большая

2022-03-01 17:25 UTC, nadyavilboa commented on project/src/components/place-card/place-card.tsx
> +    <article className={`${className} place-card`} onMouseOver={cardItemMouseHoverHandler}>
ok

2022-03-01 17:42 UTC, Finnko commented on project/src/components/place-card/place-card.tsx
> +function PlaceCard(props: PlaceCardProps): JSX.Element {
Обычно в столбик располагаю больше 3 пропсов

2022-03-01 17:49 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +};
Посмотри как ты делала жанры в киномане. Там у тебя был ключ жанр, а значение ты считала количество. Здесь у тебя ключ город, просто надо не единицу прибавлять, а пушить в массив это предложение. По типизации reduce будут проблемы - приходи в лс

По 1 пункту твой способ не решение проблемы а ее обход. Например в функции getCityNames нам forEach вообще не нужен, тоже самое можно было сделать мапом без создания массива

2022-03-06 19:03 UTC, Finnko requested changes

2022-03-06 19:03 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +    currentOffer&&setActiveOffer(currentOffer.id);
Это все удалить

2022-03-06 19:03 UTC, Finnko commented on project/src/pages/favorites/favorites.tsx
> +              {Object.entries(groupOffers).map((group: OffersGroup) => <FavoritesItem className="favorites__locations-items" group={group} key={offers.length} onMouseOver={onMouseOver} />)}
Зачем вводить новый тип, если это просто производная и можно обойтись без нее. Тс знает за счет типизации редьюса объект какого вида здесь
```suggestion
              {Object.entries(groupOffers).map(([city, offers]) => <FavoritesItem className="favorites__locations-items" city={city} offers={offers} key={offers.length} onMouseOver={onMouseOver} />)}
```
Почему key который должен быть уникальным зависит от длины массива?
FavoritesItem перенести на след строку и все ключи столбиком

2022-03-06 19:03 UTC, Finnko commented on project/src/components/favorites-item/favorites-item.tsx
> +        {offers.map((offer: Offer) => <PlaceCard className="favorites__card" offer={offer} key={offer.id} onMouseOver={onMouseOver} isSmall />)}
PlaceCard на след строку, пропсы столбиком

2022-03-08 07:56 UTC, Finnko approved these changes

2022-03-08 07:56 UTC, merged